apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:3.8
        env:
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: "postgres"
        - name: KONG_PG_DATABASE
          value: "kong" # Numele serviciului creat mai sus          
        - name: KONG_PG_PASSWORD
          value: "kong"
        - name: KONG_PG_USER
          value: "kong"
        - name: KONG_PROXY_LISTEN
          value: "0.0.0.0:5000"
        - name: KONG_ADMIN_LISTEN
          value: "0.0.0.0:8001"
        - name: KONG_ADMIN_GUI_LISTEN
          value: "0.0.0.0:8002"
        - name: KONG_ADMIN_GUI_URL
          value: "http://kong-manager.local"
        - name: KONG_ADMIN_GUI_API_URL
          value: "http://kong-admin.local"
        ports:
        - name: proxy
          containerPort: 5000
        - name: admin
          containerPort: 8001
        - name: gui
          containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: kong-service
spec:
  type: NodePort # Permite accesul din exteriorul clusterului
  selector:
    app: kong
  ports:
    - name: proxy
      port: 5000
      targetPort: 5000
      nodePort: 30000 # Mapat la portul 5000 de pe host
    - name: admin
      port: 8001
      targetPort: 8001
    - name: gui
      port: 8002
      targetPort: 8002
